### ISSUE TITLE
Provide a way to compose apps together

### ISSUE THREAD

**Issue by frank-dspeed** [donejs/donejs#1000]
lets think about something that takes a donejs-app or component and returns a app if ```XXX``` and a component when ```YYY```

also add something to read routes of apps if they are apps and combine them to a single viewModel

# use case
Sometimes you want to code a donejs-app a small one that you can run test all indipendent like a donejs app but then use that app directly as a component in a bigger app.

## Solutions:
- code a wrapper 
- code some build process (that would loose route information i think)

example:
- coding a user manager as a app
- coding some other app that uses the users but displays total diffrent stuff + the user manager

### my current solution
- donejs add app
- create routes on component usage add appName route('<appName>/{page}', { page: 'artist-list'});
- on component use remove or ignore can-route
- use a extra route.js inside your app that holds only the route viewModel
- merge stache bodys some how and stach headers or assign extra route for the app/component main

### other solution 
- create a extra bundle as component and as app.

# findings:
Gregg Roemhildt @roemhildtg 14:10
@frank-dspeed I was looking into loading ```components``` from different ```apps``` in separate project folders, and it sort of works, but I ran into an issue where It was in a file ``` project 1```, trying to load ```project2/file/file``` and imports in that file had import stuff from ```'~/other/other``` which steal interpreted as being in ```project1``` even though the file is in ```proejct2```
### Solution 
```I had set up steal's paths to use this: "project2/*": "/apps/project2/*.js"```

**Comment by green3g** [comment]
> I had set up steal's paths to use this: `"project2/*": "/apps/project2/*.js"`

This didn't fix the problem. `~/module/module` tries to load `baseProject/module/module` even though `module` is in `project1` or `project2`

For instance:
```
apps 
---- baseProject
-------- main.js --> import module from 'project1/module/module';
---- project1
-------- other
------------ other.js
-------- module
------------module.js --> import other from '~/other/other'; // tries to import baseProject/other/other
---- project2
```

I think in order for this to work, I'd need to install project1 and project2 as npm dependencies of baseProject, but that would become quite difficult to manage I think.

**Comment by justinbmeyer** [comment]
Can someone give me a short summary of what the issue is here?  

@roemhildtg `~` works if those other projects have their own `package.json`.  Do those projects have their own `package.json` and are in the `node_modules` folder?

Why is different `npm` projects difficult to manage?  We do this for the 60 projects in CanJS quite easily.  Thanks.  


If `~` isn't working, you should be able to use relative paths to make this work.

**Comment by frank-dspeed** [comment]
@justinbmeyer the main issues are the done-autorender stuff and route stuff there needs to be a structure i can't explain it short but i am working on a solution like a new generator option called multi don't found a good name last 2 weeks was a horror for me private thats why this is not done already.

its about coding a small app including routes and some components and then code a secund app that uses the other app without recoding so that each app is indipendent but can be used together

sure you can do the npm way but then still the index.stache is the problem and the main view model 

sorry that i can't supply more info today but i think you will like it as its about code reuse :)

**Comment by frank-dspeed** [comment]
apps 
  -> base project <- a donejs app
  -> some_other1 <- a donejs app
  -> some_other2 <- a donejs app
  -> problem_app <- a donejs app using some_other1 and some_other2 without recoding them

**Comment by green3g** [comment]
@justinbmeyer My use case is I'm trying to integrate one canjs app into another one. I am developing them in separate project folders because they are both serving different purposes, but I want to link them to each other, like you would in a website. Donejs comes into this conversation because if I had two different donejs apps, how do I manage them without creating two separate server instances of donejs? For example, lets say I want to run a placemyorder app with a chat app, but I don't want to require the user to log in twice? There doesn't appear to be a standard way to do this, it seems like you just need to develop the custom logic into your app template which seems odd to me, coming from a django background.. 

In my particular scenario, I'm not currently using donejs, but I didn't want to have to reload the entire app each time the user transfers between apps, so I was going to set up a can-route to navigate between the apps. Each app also uses can-route to do subpage navigation.

App1: `/{category}/{action}/{objectId}`
App2: `/{x}/{y}/{z}`

So a suggestion I received was to create a basic parent app that would create the routes and navigate between the app-components. The route would be more generic and the values would be passed to each app through a app component wrapper: `/{app}/{generic1}/{generic2}/{generic3}` 

`~` only works when the projects are npm packages. I don't want to use npm to manage these deps because they were developed as separate apps. So you're right, I should probably just change all the ~'s to relative paths.

**Comment by frank-dspeed** [comment]
@roemhildtg my implamentation idea here goes a bit more far then that i want to create a general way to use donejs apps together and combine them as they would be plugins 

but your right for your component issue in your situation the ./ relativ pathes would maybe work well

**Comment by justinbmeyer** [comment]
Thanks for the follow up.  I understand much better now.

> I don't want to use npm to manage these deps because they were developed as separate apps.

Why does developing them as separate apps mean you can't use NPM?

If I were doing this sort of thing w/ just canjs, combining `cereals-app` and `grains-app`, I would do something like the following:

## cereals app

```
cereals-app/
  package.json
  index.js
  cereals-app.js        
  cereals-app.stache
```

where `cereals-app.js` is a component like:

```
VM = DefineMap.extend({})
Component.extend({
  tag: "cereals-app"
  ViewModel: VM,
})
```

and `index.js` basically boostraps everything:

```js
route('/{x}/{y}/{z}')
var template = stache("<cereals-app>");
document.body.appendChild( template() );
```

__grains app__ would look the same.

Then I'd create a `cereals-and-grains` app that would combine them like:

```js
route('cereals/{x}/{y}/{z}',{page: "cereals"})
route('grains/{a}/{b}/{c}',{page: "grains"})
var template = stache("{{#if page}}<cereals-app>{{else}}<grains-app>{{/if}}");
document.body.appendChild( template() );
```


While this doesn't scale upward great, I think it should handle things pretty well.  To scale better, we'd need a folder-based routing system that also is able to render one app or another.

**Comment by green3g** [comment]
I kind of have a working sample of this I can share shortly. But what do you all think of using partials to render child apps?

For instance, my parent app has a progressively loaded "page" object that contains a renderer function. And my parent app template would render that page with something like this:

```handlebars
{{>header}}

{{#if pagePromise.isPending}}
<i class="fa fa-2x fa-spin fa-spinner"></i>
{{else}}
    {{#if pagePromise.isResolved}}
        {{>pageData.render}}

    {{else}}
        {{#if pagePromise.isRejected}}
            {{>error}}
        {{/if}}
    {{/if}}
{{/if}}

{{>footer}}
```

`pagePromise` is a getter tied to can-route, so if the page changes, the pagePromise gets resolved again and sets `pageData` with the new renderer. pageData would look like this:

```javascript
import renderAdmin from './templates/admin.stache';
import './styles/admin.less';

import Article from './Article';
import PersonBasic from './Person_Basic';
import PersonAdvanced from './Person_Advanced';
export default {
    render: renderAdmin,
    // add some properties for the admin page
    views: [Article, PersonBasic, PersonAdvanced],
    getActiveView (id) {
        return this.views.filter((view) => {
            return view.id === id;
        })[0];
    }
};
```

Routes can be set up in a centralized config that might look something like this:

```javascript
export default {
    routes: [
        '{page}',
        '{page}/{view}/{section}',
        '{page}/{view}/{section}/{id}'
    ],
    page: 'home',
    pages: [{
        path: 'can-admin/config/pages/home/home',
        // props for navigation links
        title: 'Home',
        iconClass: 'fa fa-home',
        id: 'home'
    }, {
        path: 'can-admin/config/pages/news/news',
        title: 'News Manager',
        iconClass: 'fa fa-news',
        id: 'news'
    }]
};
```

This seems to be pretty flexible and also pretty performant at first glance. I'll share a demo once I get some things ironed out.

**Comment by frank-dspeed** [comment]
@roemhildtg that looks really useable i at present worked on more flexible base component so we can merge that effort i think your reloading isolated state looks good but i am not sure if we will not need to modify even ssr i think ssr loads the routes and registers them on start but lets see later with your demo

**Comment by green3g** [comment]
Okay, its getting pretty close. Here's the repo:

https://github.com/roemhildtg/can-navigate

I put it up into my 'can-admin' demo app so you can get a quick proof of concept. 

http://cancrud-roemhildtg.rhcloud.com/#!home

Notes:

 - I should use more generic route variables. Probably just a, b, and c, or x, y, and z because other apps would eventually share those same routes. 
 - I will eventually add hooks for pages I'm thinking something like `beforeRender` `afterRender` and `beforeRemove` so pages can do things before they get initialized or removed, like clean up dom variables and such.

**Comment by frank-dspeed** [comment]
@roemhildtg only for your info befor you invest to much time i found out that state routing is maybe more compatible and no one needs this routing stuff because links can also set and change state so a state value and checks for that in the templates should be really good also

**Comment by matthewp** [comment]
@roemhildtg where did you get with this? Do you like the solution you came up with or do you have something more for this general issue?

**Comment by green3g** [comment]
I am pretty happy with what I came up with for the moment. I've moved all of my internal apps to use the can-navigate package and have added a lot of updates...I haven't updated the github version with my latest changes, but since I've posted that, I've incorporated a better navigation system, authentication, and other features. I gotta say having everything in a client side canjs based app is quite convenient and a lot less fragmented than using a server side templating language that loads individual client side apps. The initial load takes a bit longer but navigating between apps happens almost instantly now. 

I'm planning on updating the repo when I have more time this winter, since a lot of it right now is really specific to my organization but I will update this issue when I do so.

**Comment by matthewp** [comment]
Great to hear!

**Comment by frank-dspeed** [comment]
@roemhildtg i will update you in some weeks when its more polished i got can-webcomponet done and i am now able to combine any app can. angular vue as webcomponent.

Also did some helpers to use donejs modlet structure and stuff like can-define-webcomponent, and can-stache elements.

It allows Ultra Fast Inital SSR and also allows to return diffrent inital state then attached.

For Example Render Inital with disabled form elements and then activate once live binded.

but its a lot of stuff to document.

Some extra futures are better debug able and also define-map accessable via the component tag directly

**Comment by frank-dspeed** [comment]
i think this can be closed in favor of using webcomponents and alternativ routing solutions
https://github.com/canjsx/canjsx will have some code examples about that
