### ISSUE TITLE
Bug generate donejs donejs-chat

### ISSUE THREAD

**Issue by whdigger** [donejs/donejs#1011]
__How often can you reproduce it?__ 

- [x] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Description:__
I try generate new application use guide https://donejs.com/Guide.html but don't work correct, get error message. I try use Ubuntu 14.04.4 LTS and also does not work
```
ENOENT: no such file or directory, open '/var/www/done/donejs-chat/node_modules/npm/node_modules/update-notifier/node_modules/configstore/package.json.1306941151'
npm ERR! enoent This is related to npm not being able to find a file.
```

__Steps to reproduce:__

1. curl -sL https://deb.nodesource.com/setup_8.x | sudo bash -
2. sudo apt-get install -y nodejs git
3. sudo npm install -g donejs@1
4. donejs add app donejs-chat

__Expected results:__
https://pastebin.com/bBCu9BnG

__Actual results:__
Done compleated

__Environment:__

| Software                | Version
| -------------------------| -------
| virtual-box             |  5.1.22r115126
| donejs -V               |  1.0.1
| node -v                  |  8.4.0
| npm -v                   |  5.3.0
| Browser                 | 
| Operating system  |  Debian GNU/Linux 9.1 (stretch) | Linux 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u2 (2017-06-26) x86_64 GNU/Linux

**Comment by matthewp** [comment]
Hey, I was able to get it to work: 

<img width="1020" alt="screen shot 2017-08-18 at 1 56 15 pm" src="https://user-images.githubusercontent.com/361671/29471103-bf372b22-841c-11e7-87c3-52e21835e083.png">


The thing I would suggest doing is not use the Ubuntu-provided Node.js, because it is usually out of date.  Instead I would recommend installing [nvm](https://github.com/creationix/nvm) and use a version from there.

**Comment by matthewp** [comment]
Closing for now.
