### ISSUE TITLE
PMO: SSR doesn't include the `href`s on the navigation links

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/donejs#1154]
If you look at the network tab and scroll to the navigation HTML, you see:

![image](https://user-images.githubusercontent.com/78602/50298498-e6530b00-0444-11e9-83e9-8692f4c4012f.png)

Looks like `.href` attributes/properties are not being serialized.

**Comment by matthewp** [comment]
Does stache prefer setting `.href` rather than the attribute perhaps?

**Comment by justinbmeyer** [comment]
That’s what I was thinking. It would be in can-attribute-observable

**Comment by matthewp** [comment]
Looks like this is in prod on `www.place-my-order.com` so this has likely been happening for a while.

**Comment by matthewp** [comment]
https://github.com/canjs/can-attribute-observable/blob/a822ee6aa7940920143069079a0515caf5902af1/behaviors.js#L480 .

That is truthy so it sets the property. That's truthy because there is an empty string href.  I'm not sure what actually adds the property initially.

Not sure what the best solution is yet, one possibility is for can-simple-dom to add a setter for href so that it reflects back onto attributes.

**Comment by matthewp** [comment]
can-simple-dom assigns the href property on initialization. I think adding a setter that reflects onto attributes is the best approach here.

**Comment by matthewp** [comment]
https://github.com/canjs/can-simple-dom/pull/90

**Comment by matthewp** [comment]
This is fixed: view-source:http://www.place-my-order.com/

<img width="573" alt="screen shot 2018-12-27 at 11 19 31 am 1" src="https://user-images.githubusercontent.com/361671/50486745-5cb5b700-09c9-11e9-86a4-f50523793816.png">
