### ISSUE TITLE
mobile menu

### ISSUE THREAD

**Issue by moschel** [donejs/donejs#144]
The menu shows all the bitovi links in bold and without hierarchy, which looks weird. It also seems to imply that the blog link is for DoneJS.

2 options.

1) We remove everything except one link to Bitovi. 
2) We make the hierarchy clear with indentation.

I vote for nbr 1. Not sure the rest are needed on mobile.

![img_3073](https://cloud.githubusercontent.com/assets/22180/10409275/911eea72-6ede-11e5-97ad-8f929364b1ce.PNG)

**Comment by atomgroom** [comment]
@moschel Yes, you're right it does look a bit off still.  

I am normally against removing things from a responsive site, if the only reason is that it's the mobile view.  Rather, I like to design an alternative solution.   But in this particular case, I do think you're right and it can be removed.  I also think that we should remove the Bitovi.com link because all of that information is all available on the About page, which is already in the menu.

Here's the proposed redesign:
![screen shot 2015-10-12 at 6 59 40 pm](https://cloud.githubusercontent.com/assets/5687712/10441893/8856877e-7113-11e5-8b3f-17999a0df678.png)
