### ISSUE TITLE
hover text

### ISSUE THREAD

**Issue by moschel** [donejs/donejs#146]
Super minor and probably not even worth the time it takes to write this, but its been bugging me. The font looks all pixelated and weird when you hover in the Bitovi menu. Not the same as the guides menu font for some reason. Shouldn't these be the same fonts?

![2015-10-09_2340](https://cloud.githubusercontent.com/assets/22180/10409284/4cd9b88c-6edf-11e5-957f-e03704c51735.png)

**Comment by atomgroom** [comment]
@moschel I am not sure what you mean.  I looked into this and from what I can see all the dropdown menu items have the same font, font-size and hover interactions.

![screen shot 2015-10-12 at 12 27 18 pm](https://cloud.githubusercontent.com/assets/5687712/10434064/c6ab7908-70dc-11e5-924a-bd0db4285648.png)

**Comment by atomgroom** [comment]
@moschel I can definitely see how some characters have a bit of blurring on them, but unfortunately I am unable to smooth them out any more.  

I tried several different CSS tweaks to anti-aliasing and none of them do anything except make the font a bit more bold - but if you zoom in, they still have the same blurring.  I am going to assume that this is just the font itself, mostly because it's the same on all of our other websites too. I believe that it is also due to our monitors.  On my retina laptop, the font looks very crisp and beautiful.
