### ISSUE TITLE
docs and guides buttons

### ISSUE THREAD

**Issue by moschel** [donejs/donejs#180]
@skylerraytaylor Justin was telling me that you made a design for the features page that included buttons that link to the guide and documentation for each feature. Could you point me to that?

I'd like @atomgroomdesign 's help adding those.

**Comment by skylerraytaylor** [comment]
@moschel Here is the mockup I originally did. The idea was that there would be links to the guide/documentation/project for each feature. We ended up using a light background for the code examples instead of a dark background, so ignore that. ![donejs-features-page-02](https://cloud.githubusercontent.com/assets/3943219/10456063/baa7c276-7184-11e5-9fcb-edad6987ee16.jpg)

**Comment by atomgroom** [comment]
@skylerraytaylor Thanks!

@moschel I think the best way to implement this would be to use a CSS class in the Markdown so that all of the other `<a>'s` don't inherit the button style.

`<a href="foobar.html" class="btn">View the Guide</a>`

**Comment by moschel** [comment]
Thanks Skyler. @atomgroomdesign could you please implement this class? I'd like to add them
