### ISSUE TITLE
titles at the top

### ISSUE THREAD

**Issue by moschel** [donejs/donejs#183]
@atomgroomdesign this is minor, but could you put the titles for the images below at the top? It is confusing with them at the bottom, I had to study it for a second to understand which was which.

![2015-10-13_0205](https://cloud.githubusercontent.com/assets/22180/10447991/10550c78-714f-11e5-9b74-4085f41f652b.png)

**Comment by justinbmeyer** [comment]
Labels for images are usually at the bottom.

**Comment by atomgroom** [comment]
@moschel I can see how you think it's confusing with the label on the bottom.  

Although, @justinbmeyer is correct, labels or captions are usually at the bottom.  Moving them to the top will only shift the same exact issue in the other direction for users that are familiar with this pattern.

I think the real issue here is spacing and separation between these two images. Do you think that will help make this less confusing for you?

**Comment by moschel** [comment]
Nah forget it, its minor. If you guys think its not confusing then its fine.
