### ISSUE TITLE
Comparison Matrix

### ISSUE THREAD

**Issue by julia-allyce** [donejs/donejs#186]
Create a matrix comparing DoneJS Features with other libraries.

**Comment by atomgroom** [comment]
Notes:
X-Axis: Frameworks
Y-Axis: Features

**Comment by atomgroom** [comment]
@julia-allyce @moschel 

Here's my first take at a comparison graph for the site.   I really like the idea of using Emoji's because I think so many people understand them today, regardless of demographics.  Additionally, they express more emotion than the consumer reports icons.  You can almost understand what the emoji means, without referencing the legend.

I started with regular emjoi's which is sort of the fast and easy approach.  It works, but once you put a lot of them in the grid, it tends to get confusing because of how close the colors are.

![donejs-comparison-v001](https://cloud.githubusercontent.com/assets/5687712/10491785/fb385de8-726d-11e5-9be3-fff889c147a5.jpg)

In the next iteration below, I use emoji's but go with flat colors and unique color for each.  So now, we get the emotion of the emoji itself and also the color spectrum. Green = Good down to Red = Poor.  I decided to keep "All the Things" because it's awesome. 

![donejs-comparison-v002](https://cloud.githubusercontent.com/assets/5687712/10491828/3d548cba-726e-11e5-9dde-5357e9e55b38.jpg)

Please let me know your thoughts.

**Comment by marshallswain** [comment]
@atomgroomdesign when I looked at the first one, I thought it would be nice if you used color, so you really came through immediately when I clicked on the second one.  Color is way better, imo.  

Looking at the color one, I think it would be nice if you could use color boldness (I'm no designer, so this is what I'm calling it) to draw attention to the ones that perform the best.  Kinda like making them stand out the way  big bold action buttons would stand out, and the ones that suck kinda fade into the shame of their nothingness.  But I really like the "All The Things" guy as the epitome of awesomeness.  If there were a way to keep him and still use boldness to make things stand out, that would be cool.  In the current color example, the red and blue color kind of demand the same amount of attention.

imo

**Comment by atomgroom** [comment]
@marshallswain 
Cool. Thanks for the feedback.  Brian mentioned the same earlier today.  I'll have to play around with the colors a bit more.  Brian mentioned lowering the opacity of the middle tier colors so the extreme end colors get the attention you speak of.

Although, I would like to add a feature for when the user hovers an icon in the legend - that icon gets highlighted and all others lower in opacity.   So, the opacity above, would conflict.  I think just going with more subtle colors will be the right approach.

**Comment by atomgroom** [comment]
Here's another iteration with all the above feedback considered:

![donejs-features-page-v3](https://cloud.githubusercontent.com/assets/5687712/10498997/5d319634-7293-11e5-9f78-b7f6ee990cef.jpg)

**Comment by matthewp** [comment]
I think a 1-5 rating is a bad idea. People are already skeptical about comparisons. Giving ratings will just make peoples' eyes roll.

Take the subjectivity out of the equation. Does the framework support the feature or not?  If the answer is "kinda" put an asterisks and explain it.
