### ISSUE TITLE
ECS - A coffeescript version of EJS

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/donejs#20]
I'd like to make EJS more powerful

Functions are likely to become more popular w/i EJS.   But they are cumbersome.  

I'd like to make a coffeescript version of ejs. It could look like:

```
<%+ formFor model,  (f) -> %>
   <%= f.input "name" %>
<%-%>
```

The problem is indention.  I'm thinking tags like `<%+` and `<%-` could be used to control indention.

**Comment by polgfred** [comment]
You can assume that certain constructs will create an additional level of indentation: a function decl, if/else/do/while, etc. As for when to end an indentation block, you can do it with some kind of 'end' token. The convention in Django templates is to use "endxxx" where xxx is whatever begins the loop:

```
<% for foo in bar: %>
  <%= foo %>
<% endfor %>
```

Since there is no `end` keyword in CS, you can probably just always use `end` to denote a dedent.

**Comment by justinbmeyer** [comment]
I'm not sure if that will work ... how would we know where the indent begins (w/o a lot of work in ejs)?

**Comment by polgfred** [comment]
Like I said, certain constructs always create an indent. Yes, you'd actually have to parse it. The only other way is to make the indentation of the ECS file itself significant, which really sucks IMO.

**Comment by polgfred** [comment]
Sam Stephenson just published Eco for this. Worth taking a look for inspiration at least.

https://github.com/sstephenson/eco

I like the idea of using the colon to denote indentation, and `end` to dedent.

**Comment by justinbmeyer** [comment]
Ah, it also supports blocks and capturing, another feature I wanted ....

**Comment by justinbmeyer** [comment]
EJS now supports blocks and capturing.
