### ISSUE TITLE
NPM packaging buttons

### ISSUE THREAD

**Issue by moschel** [donejs/donejs#264]
There are 2 features for the section below, so I added a second button

1) please align these (and test on other breakpoints)
2) I changed it from Learn More to the name of each feature. Any recommendations on how to make this more consistent with the pattern of the rest of the sections? Or should we just leave it like this.

![2015-10-21_0151](https://cloud.githubusercontent.com/assets/22180/10629661/6138b606-7796-11e5-9e61-a79fb9295203.png)

**Comment by atomgroom** [comment]
@moschel I do think for that section that it makes sense to change up the naming convention of the buttons.  But, I wonder if it would be too much to follow that pattern in the other sections.

Documentation - For example:

1) You have the video image with the title: Documentation
2) Then the caption title: Documentation
3) Button Text: Documentation

That's the same word repeated three times in one section.  Buttons serve as a _call to action_, so in this sense, "Learn More" serves that purpose.  We could change them to something like "Read More", "Read the Docs", if you like that or have any other ideas?

For now, I'll update the CSS so that they layout correctly in all the responsive views.
