### ISSUE TITLE
Blog Article

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/donejs#301]
- [x] DoneJS logo
- [x] Node process behavior
- [ ] Performance from homepage.
- [x] Longevity
- [ ] Mountain climb 
## Longevity

![image](https://cloud.githubusercontent.com/assets/78602/10735103/58aacbf4-7bd4-11e5-9af2-d89a3162409c.png)

I need this with JMVC stretching it's whole history and having CanJS, StealJS, jQuery++ sort of stretch out with it.
## Mountain climb

A more professional version of:

![image](https://cloud.githubusercontent.com/assets/78602/10740810/47cd88ee-7bf2-11e5-829a-98b1d5f0d04f.png)
## Performance from homepage

I'd like a version of the performance image from the homepage that I can stick in the `Faster loading sites` section.

**Comment by justinbmeyer** [comment]
cc @atomgroomdesign @skylerraytaylor

**Comment by atomgroom** [comment]
Logo:

https://raw.githubusercontent.com/donejs/donejs/master/docs/theme/static/img/donejs-logo-ie.png

**Comment by justinbmeyer** [comment]
@atomgroomdesign thanks.  Should I use that or use one that fits perfectly within our blog's width?

**Comment by atomgroom** [comment]
@justinbmeyer That image should scale and look nice as it is. If you do have issues, just let me know and I'll correct.

**Comment by skylerraytaylor** [comment]
![longevity](https://cloud.githubusercontent.com/assets/3943219/10744558/cbde916c-7c08-11e5-81f2-dbf9a37ded24.jpg)

**Comment by moschel** [comment]
Was StealJS really released in 2014? I think it was before that.

**Comment by skylerraytaylor** [comment]
@justinbmeyer said it was May 2014

**Comment by skylerraytaylor** [comment]
![mountain-climb](https://cloud.githubusercontent.com/assets/3943219/10744617/49667cd0-7c09-11e5-9ea4-a1b6947665e7.jpg)

**Comment by moschel** [comment]
I don't think the team velocity Y axis makes sense anymore in this new context. I would get rid of that and just make it a more traditional timeline, or change the Y axis to something more relevant.

**Comment by justinbmeyer** [comment]
@skylerraytaylor Please:
- remove the Y axis label.  
- add in CanJS 2.3 right before DoneJS
- make JMVC 3.3 come after CanJS 1.0

I think the line looks fine, but ideally it would show a little dip right as people hit the next release, and then acceleration after.

Maybe in contrast to this, we have another image which might show "starting from 0" again.  With a new incompatible release.

**Comment by pstrozak** [comment]
1.) The beginning of the first sentence could be smoother...  "After two years since JavaScriptMVC 3.3 was released, today we are announcing DoneJS - the easiest way to you get your amazing application done!" and the second part  "the easiest way to (for?) you (to?) get your amazing application done!" needs to be updated.

Suggestions:  "Today, two years after JavaScriptMVC 3.3 was released, we are excited to announce ...!"  or "In 2013 we released JavaScriptMVC 3.3 and today we are excited to announce DoneJS...." or "After releasing JavaScriptMVC 3.3 two years ago, today we are announcing DoneJS... "

2.) Add a link to the getting started guide to take readers there as soon as they finish reading "And if you haven’t yet checked out donejs, start now with the **getting started guide**."

3.) Replace then with than: "We are going to bring more **then** $5 of swag per person to every event"

4.) Is there anyway to set all the links to open up in a new window vs. on the same page over the article?

**Comment by moschel** [comment]
1. "We needed to get everyone on to NodeJS and onto CommonJS, AMD or ES6 modules." - on to should be one word, onto
2. The logo in the intro should link to donejs.com, not a logo image. also, I'd make the first time you mention DoneJS be a link to the site.
