### ISSUE TITLE
support for sidebars

### ISSUE THREAD

**Issue by moschel** [donejs/donejs#392]
It would be very nice to able to add a "sidebar" in the guides.

Something like this:

![2015-10-29_2135](https://cloud.githubusercontent.com/assets/22180/10837257/25fda286-7e85-11e5-8c1b-3c8f51f86d35.png)

This would be appropriate for things like discussing windows specifics, or explanations about topics that aren't required to complete the guide.

**Comment by atomgroom** [comment]
@moschel Here's a clean example that would be easy to implement.  Please let me know your thoughts.  

I considered putting a little coffee cup icon to the left of the heading, so that readers are familiar with that icon.   A water cooler icon could be funny too.  Either could potentially help readers understand that this is a sidebar conversation, or deeper thought of something in particular.  Meteor's yellow implementation is certainly interesting, at first glance it looks like a big warning about something above it.

![donejs-sidebars-001](https://cloud.githubusercontent.com/assets/5687712/10848639/fa848730-7eea-11e5-982c-fe876e4ee5d5.png)

**Comment by moschel** [comment]
I like it. I don't think it needs an icon though. I don't think its worth a lot of effort though, is this something that won't take long to implement?

**Comment by atomgroom** [comment]
Here's the markup to use in your markdown files:

```
<div class="section-details">
  <h3>Details Heading</h3>
  <p>Nulla gravida tellus vitae sollicitudin faucibus. Praesent rutrum quam sit amet lorem ultrices, iaculis rhoncus risus pretium. Proin varius nunc leo, vel hendrerit purus volutpat eu. Aliquam bibendum metus tempus aliquet fermentum. Pellentesque sit amet auctor lorem. Nullam fermentum nisi in accumsan posuere. Vestibulum ultricies et libero nec tincidunt.</p>
</div>
```

**Comment by justinbmeyer** [comment]
Couldn't we just use blockquote which markdown supports?

**Comment by atomgroom** [comment]
Hi @justinbmeyer 

Yes, we can.  However, it's not semantic because it's not really a blockquote.

"The `<blockquote>` tag specifies a section that is quoted from another source.".  

We're not quoting another source, this section-details is an contextual in-depth note about something specific related to the section it is in.

**Comment by justinbmeyer** [comment]
I'm alright with it not being semantic.  Piratically, it makes sense to get blockquote looking like the aside @moschel had above.  We an aside need 20 times more than a semantic quote.

As markdown makes blockquote so easy:

> this is some "aside" information.

I think we can double use blockquotes and asides pretty safely.  (this is something we probably want for documentjs too).

**Comment by atomgroom** [comment]
Hi @justinbmeyer 

I think that's a very valid point.  In other words, usability is a higher priority than being semantic.  I also really like the `aside` idea.  It's actually more semantic than either, because that is what that element is for.

I have updated the "sidebar-section-design" branch so that blockquotes using markdown `>` and also a `<aside></aside>` coded in a markdown file will result in the same style and design.

The top element is a blockquote and the bottom is an aside:

![screen shot 2015-11-02 at 8 52 25 am](https://cloud.githubusercontent.com/assets/5687712/10885035/e2a1dbba-8140-11e5-9c7b-53f1e8e73f46.png)
