### ISSUE TITLE
We need a generator that creates a skeleton for a plugin project.

### ISSUE THREAD

**Issue by marshallswain** [donejs/donejs#447]
This would make it much easier to start a new project.  Based on this forum conversation: http://forums.donejs.com/t/packaging-can-components-for-reuse/90

**Comment by thecountofzero** [comment]
After thinking about this a bit, wouldn't we just use:

`donejs add component messages chat-messages`

Or does this just add a component to an app? If so, could still do this and strip away the unneeded?

**Comment by matthewp** [comment]
That doesn't give you everything you need, you want a build script to build the component out to AMD/CommonJS/Global as well. Sure, you can turn a normal donejs project into a Component project though.

**Comment by thecountofzero** [comment]
What would a Component project look like? You mentioned bit-tabs as an example, however, bit-tabs does not follow the modlet pattern as described on the donejs website. I like the modlet pattern. I guess the only thing missing is the tests that are in their own directory. And maybe the fact that both bit-tabs and bit-panel are in the same directory.

**Comment by justinbmeyer** [comment]
Bit-tabs is mostly just an extreme version of the modlet pattern.   The modlet pattern is that every "useful" module has its own folder and everything goes within that folder.  By "useful", I mean that `stache` and `less` files that are associated with a component are not "useful on their own".  So a module might include a lot of other sub-modules.

To be clear ... a "component" project should really be about one component.  We aren't (I think) talking about a project of lots of components / widgets.

Bit-tabs is a little strange because it packages bit-panel, but its structure pretty much what a component project should look like.

Tests are in their own directory, but there's only tests for the behavior of a single module.  

For even more simple components, the `src` and `test` folder are probably not even needed.  All files could probably be directly in the root folder.

**Comment by thecountofzero** [comment]
Be a good idea to get either a generator or an example out there showing people how this should be done. I've been scouring the donejs site and some of the stuff on github.com and it can quickly become confusing on the "right" way to do things as there are so many possible ways. Getting everyone on the same page and developing with the same patterns can go a long way within the DoneJS community.

I am mostly talking about single component projects, but it would be useful to have a guide for creating libraries of components. Then there's bit-tabs which really needs to include a second component (bit-panel), because without bit-panel, bit-tabs is kind of useless.

Should tests be in their own folders? The modlet pattern makes a strong case against this...

**Comment by justinbmeyer** [comment]
@thecountofzero 

> Should tests be in their own folders? The modlet pattern makes a strong case against this...

If there are a bunch of "useful" modules, yes.  But in the case of bit-tabs, there's really only one useful module.  Like I mentioned in the previous comment ... when you put every module in it's own repository ... you have the "modlet" pattern by default ... regardless of where your tests are.

**Comment by justinbmeyer** [comment]
Just to help make sure we are on the same page.  The modlet pattern is there to:
- make sure that in a big application, people aren't forgetting about tests because they are hidden "far" away from the actual source
- be able to work in one limited area of the filesystem.

When you have a single small module in its own repo, these concerns become largely irrelevant.  That's why I'm saying that putting everything in its own repo is just an "extreme" version of the modlet pattern.  Not only are tests/demos/etc local to the module being worked on, so are it's package dependencies, it's build, it's versioning, etc.

**Comment by justinbmeyer** [comment]
Currently, the best things to look at are `bit-tabs` and `can-connect`.  `bit-tabs` because it's showing a component(s) pattern.  `can-connect` for it's release scripts: https://github.com/canjs/can-connect/blob/master/package.json#L83 .  `can-connect` is able to push out a built version of itself and a git version tag that includes the `dist` build.  It's amaze-balls.

**Comment by thecountofzero** [comment]
Word!

**Comment by matthewp** [comment]
@daffl will be writing an article about how to use this.

**Comment by malamoney** [comment]
Has @daffl written said article yet?

**Comment by marshallswain** [comment]
Its coming very soon.

**Comment by daffl** [comment]
It's in the review phase. We're shooting for Thursday.
