### ISSUE TITLE
PMO Guide - Deploy 

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/donejs#465]
For the deploy part of the PMO guide, if possible, it should:
- Use heroku's ability to watch for changes in master and update the deployed app.
  - It will probably need to do a build with a post install hook so nothing needs to be checked in.
- Make sure the deploy also does the static deploy (I'm not seeing this currently, does it deploy on a change?).
- Show people how to make a change, push to a branch, wait until the test passes and merge into master.

**Comment by matthewp** [comment]
I don't think this is good advice. Generally speaking you should not be doing builds on an app server. That's what a build server is for. Since we are using a build server, Travis, I do not see an advantage to doing it this way. The only advantage is maybe that you don't have to force-push to Heroku.

**Comment by justinbmeyer** [comment]
@matthewp well, this is the CI / test server really right?  

Originally, we were going to use Heroku's ability to watch `master` and deploy on its own.  

Yeah, the advantage is that you don't have to force-push, but if we aren't using Heroku to watch things, I agree that the "add-to-dist and force-push" probably makes sense.
