### ISSUE TITLE
Server-side live-reload

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/donejs#66]

**Comment by matthewp** [comment]
Biggest problem I foresee here is that we need a web socket client in Node to connect to the server.  But since we are running in the context of the user's problem we can't simply require() one.  Probably what we'll need to do is find a simple one and include it in Steal's `ext/` folder and require it using require.resolve() to find the path.

**Comment by daffl** [comment]
Couldn't we just shim the global `WebSocket` that's used in https://github.com/stealjs/live-reload/blob/master/live.js#L243 (like we already do with `XMLHttpRequest`)?

**Comment by matthewp** [comment]
By putting the shim code in can-ssr?  Could do that, but then this would only work if you are using can-ssr (maybe that's ok).

**Comment by daffl** [comment]
You mean when running `can-serve`? I would think that's ok since we already do that with XMLHttpRequest (although we might just be able to add that to the middleware).

**Comment by matthewp** [comment]
Working on this now:

Notes:

* [ ] - Need to have a way to toggle live-reload off (probably a config option).  This will require a minor bump.
* [ ] - Need to provide the host name so that live-reload connects to the correct place.
