### ISSUE TITLE
Update the Minimal DOM Updates section with CanJS 3 vs. React 15

### ISSUE THREAD

**Issue by chasenlehara** [donejs/donejs#839]
The Minimal DOM Updates section on the [features page](https://github.com/donejs/donejs/blob/major/docs/features.md) should be updated to compare CanJS 3’s performance to React 15.

**Comment by matthewp** [comment]
@ccummings I see that you might have been part of making the gist. Is the donejs todomvc and react mvc code that was used for those somewhere?

**Comment by christopherjbaker** [comment]
I updated react to 15.4.2. It is still using canjs 2.3. I attempted to update it to the latest, but don't know enough about it to migrate. http://jsbin.com/zigovul/edit?html,js,output

**Comment by christopherjbaker** [comment]
I updated react to 15.4.2, though I'm having some trouble upgrading canjs to 3.5.1. http://jsbin.com/zigovul/edit?html,js,output

**Comment by bmomberger-bitovi** [comment]
@christopherjbaker Your donejs script is cut off before the end (in the original gist it's going to line 20490).  Looks like you might have needed to paste in more lines.

**Comment by christopherjbaker** [comment]
Yes, gist didn't seem to like how long the file was (as I was using an unminified version of can-all). My local complete copy was not working either, which is why I didn't update it.

With lots of help from @nlundquist, I got the can 3.5.1 version working (see previously linked jsbin). There was no significant change to CanJS performance, and there was a slight increase to React performance at high counts.
