### ISSUE TITLE
Clicking on "Pretty URL’s with Pushstate" does not bring you to that section

### ISSUE THREAD

**Issue by rlin415** [donejs/donejs#874]
![demo](https://cloud.githubusercontent.com/assets/8172613/24432236/9f468bbc-13d5-11e7-933f-f1699175b971.gif)

**Comment by phillipskevin** [comment]
@Rlin415 would you mind testing this on the DoneJS 1.0 site: https://donejs.github.io/donejs-next/ also?

**Comment by rlin415** [comment]
@phillipskevin Looks like none of the links that are experiencing this same issue are happening in the DoneJS 1.0 site.

**Comment by chasenlehara** [comment]
We’re probably going to launch the new site in the next couple weeks, so if you can’t reproduce it in the test site, you can close these issues.

Also, for an issue that manifests itself in multiple places, feel free to file one issue that lists those places instead of creating individual issues for each.
