### ISSUE TITLE
Community links blocked on mobile

### ISSUE THREAD

**Issue by andrejewski** [donejs/donejs#928]
On mobile, I cannot click the community links because they are covered with an invisible div:

<img width="601" alt="screen shot 2017-04-27 at 1 50 02 pm" src="https://cloud.githubusercontent.com/assets/1660953/25496899/b2c375be-2b50-11e7-96c8-6af9f5325ca5.png">

(Visible on desktop on a narrow screen.)

**Comment by gpetrioli** [comment]
Just a note for the above PR.

The problem was not an invisible `div`. The overlapping element was the container of the help/upcoming/contribute links, which has a top padding. Converting that to margin and zeroing the padding pushed the container down enough to allow the links to be interactive and maintained the initial look.

**Comment by matthewp** [comment]
Wow! Thank you for fixing this, what an awesome contribution!

**Comment by matthewp** [comment]
Going to keep this open until we deploy the fix.

**Comment by matthewp** [comment]
This was deployed. Thanks again @gpetrioli

**Comment by justinbmeyer** [comment]
Yes, thanks @gpetrioli !!!
