### ISSUE TITLE
How about use electrino?

### ISSUE THREAD

**Issue by xedoken** [donejs/donejs#940]
I found this:

https://github.com/pojala/electrino
https://medium.com/dailyjs/put-your-electron-app-on-a-diet-with-electrino-c7ffdf1d6297

And great article in medium for diffing electron and electrino. I think that electrino is super cool with electron api support. Comparison of identical “Hello World” apps between Electron and Electrino: the latter is only 167 KB in size. That’s only 0.1% percent of the size of the Electron app (the Electrino app is almost a thousand times smaller!). What do you think? Can you integrate this?

**Comment by phillipskevin** [comment]
I think Electrino looks really interesting, but right now it seems more like a proof-of-concept than something that can be used in apps. Also, since it doesn't have support for many of the Electron APIs right now it would be difficult to integrate.

I think it's a really interesting project to watch, but not something we can use right now.

I'm going to close this for now, but feel free to re-open if you think there is a viable way to integrate Electrino into DoneJS.
