### ISSUE TITLE
DoneJS Slim Loader Integration

### ISSUE THREAD

**Issue by matthewp** [donejs/donejs#957]
This is an epic for getting the new slim loader working in DoneJS apps.

**Comment by frank-dspeed** [comment]
@matthewp https://github.com/direktspeed/donejs-slim

ready to implament it and make pull request once you show me where that slim loader is :D

**Comment by frank-dspeed** [comment]
@matthewp as this slim loader is in now what would you suggest to make that happen?
- codemods for that via a donejs-slim generator?
- Close this and deprecate It because of https://github.com/donejs/donejs/issues/958?

**Comment by matthewp** [comment]
If you download zenhub you can see the issues associated with this "Epic".

**Comment by frank-dspeed** [comment]
@matthewp i watched now and installed it for chrome and there are only the both options that i have asked about or zenhub is not working right so my question remains is this epic still valid because Justin suggests to make this the default behavior 

if this is really only related to the one issue of creating a donejs-slim then i only need to add the codemod for that and its done as i prepared a generator biolerplate

and i think this is blocking to make this default for donejs https://github.com/donejs/done-ssr/issues/254

**Comment by matthewp** [comment]
No, this is an issue that encapsulates many other issues, not just a generator.

**Comment by frank-dspeed** [comment]
@matthewp why can't i see all this related stuff with zenhub? would i need to be added to this organization for that? it shows only 2 issues in the board and also here: DoneJS Slim Loader Integration has no dependencies

**Comment by frank-dspeed** [comment]
@matthewp ah i think i got it 
there is a small list of related issues now! thanks for information.

**Comment by matthewp** [comment]
This was completed.
