### ISSUE TITLE
donejs deploy fails

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/donejs#963]
Doing the steps in the [DoneJS Chat: Configure DoneJS Guide](https://donejs.com/Guide.html#configure-donejs) fail.  

<img width="895" alt="cursor_and_donejs-chat_ _-bash_ _59x31" src="https://user-images.githubusercontent.com/78602/27145871-e10f7b6c-50fc-11e7-9601-ed4b57c14cfb.png">

I am only really running `donejs add app` followed by the steps to do a deploy. To re-create:

- `donejs add app donejs-chat`
- `cd donejs-chat`
- create a new app in the firebase console: https://console.firebase.google.com/
- `donejs add firebase`
- `node_modules/.bin/firebase login`
- `donejs build`
- `donejs deploy` - fails

**Comment by justinbmeyer** [comment]
Possibly related: https://github.com/firebase/firebase-tools/issues/369

https://github.com/firebase/firebase-tools/issues/342

**Comment by matthewp** [comment]
I was able to recreate. Investigating.

**Comment by matthewp** [comment]
I'm thinking the file format might have changed in some way, looking into that.

**Comment by matthewp** [comment]
I think it's because the firebase ID is incorrect. When I tried it I typed in the **name** I chose when creating the firebase. https://console.firebase.google.com/

However, that's not the firebase ID.

<img width="325" alt="screen shot 2017-06-14 at 1 59 00 pm" src="https://user-images.githubusercontent.com/361671/27147155-be09ecda-5109-11e7-8469-b5a227980d92.png">

In this example the firebase ID is **deployed-app-cd29b**. Changing my `.firebaserc` file with that ID fixed it for me.

**Comment by matthewp** [comment]
Also going to change:

```
"node_modules/.bin/firebase deploy --token \"$FIREBASE_TOKEN\""
```

to:

```
"npm run deploy:ci"
```

**Comment by matthewp** [comment]
* [x] - Release donejs-firebase with wording change.
* [x] - Update chat-guide with UI to get the id.
* [x] - Update PMO guide with UI to get the id.
* [ ] - Update PMO guide to use `npm run deploy:ci` in Travis setup.
